---
title: "Create Combined CSV File"
output: github_document
---
```{r library, message = FALSE}
library(tidyverse)
```

```{r 1950}
StormEvents_1950 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1950_c20250520.csv")
StormEvents_1950 <- StormEvents_1950|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1951}
StormEvents_1951 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1951_c20250520.csv")
StormEvents_1951 <- StormEvents_1951|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1952}
StormEvents_1952 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1952_c20250520.csv")
StormEvents_1952 <- StormEvents_1952|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1953}
StormEvents_1953 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1953_c20250520.csv")
StormEvents_1953 <- StormEvents_1953|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1954}
StormEvents_1954 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1954_c20250520.csv")
StormEvents_1954 <- StormEvents_1954|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1955}
StormEvents_1955 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1955_c20250520.csv")
StormEvents_1955 <- StormEvents_1955|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1956}
StormEvents_1956 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1956_c20250520.csv")
StormEvents_1956 <- StormEvents_1956|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1957}
StormEvents_1957 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1957_c20250520.csv")
StormEvents_1957 <- StormEvents_1957|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1958}
StormEvents_1958 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1958_c20250520.csv")
StormEvents_1958 <- StormEvents_1958|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1959}
StormEvents_1959 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1959_c20250520.csv")
StormEvents_1959 <- StormEvents_1959|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1960}
StormEvents_1960 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1960_c20250520.csv")
StormEvents_1960 <- StormEvents_1960|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1961}
StormEvents_1961 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1961_c20250520.csv")
StormEvents_1961 <- StormEvents_1961|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1962}
StormEvents_1962 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1962_c20250520.csv")
StormEvents_1962 <- StormEvents_1962|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1963}
StormEvents_1963 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1963_c20250520.csv")
StormEvents_1963 <- StormEvents_1963|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1964}
StormEvents_1964 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1964_c20250520.csv")
StormEvents_1964 <- StormEvents_1964|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1965}
StormEvents_1965 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1965_c20250520.csv")
StormEvents_1965 <- StormEvents_1965|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1966}
StormEvents_1966 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1966_c20250520.csv")
StormEvents_1966 <- StormEvents_1966|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1967}
StormEvents_1967 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1967_c20250520.csv")
StormEvents_1967 <- StormEvents_1967|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1968}
StormEvents_1968 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1968_c20250520.csv")
StormEvents_1968 <- StormEvents_1968|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1969}
StormEvents_1969 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1969_c20250520.csv")
StormEvents_1969 <- StormEvents_1969|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1970}
StormEvents_1970 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1970_c20250520.csv")
StormEvents_1970 <- StormEvents_1970|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1971}
StormEvents_1971 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1971_c20250520.csv")
StormEvents_1971 <- StormEvents_1971|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1972}
StormEvents_1972 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1972_c20250520.csv")
StormEvents_1972 <- StormEvents_1972|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1973}
StormEvents_1973 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1973_c20250520.csv")
StormEvents_1973 <- StormEvents_1973|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1974}
StormEvents_1974 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1974_c20250520.csv")
StormEvents_1974 <- StormEvents_1974|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1975}
StormEvents_1975 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1975_c20250520.csv")
StormEvents_1975 <- StormEvents_1975|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1976}
StormEvents_1976 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1976_c20250520.csv")
StormEvents_1976 <- StormEvents_1976|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1977}
StormEvents_1977 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1977_c20250520.csv")
StormEvents_1977 <- StormEvents_1977|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1978}
StormEvents_1978 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1978_c20250520.csv")
StormEvents_1978 <- StormEvents_1978|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1979}
StormEvents_1979 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1979_c20250520.csv")
StormEvents_1979 <- StormEvents_1979|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1980}
StormEvents_1980 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1980_c20250520.csv")
StormEvents_1980 <- StormEvents_1980|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1981}
StormEvents_1981 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1981_c20250520.csv")
StormEvents_1981 <- StormEvents_1981|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1982}
StormEvents_1982 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1982_c20250520.csv")
StormEvents_1982 <- StormEvents_1982|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1983}
StormEvents_1983 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1983_c20250520.csv")
StormEvents_1983 <- StormEvents_1983|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1984}
StormEvents_1984 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1984_c20250520.csv")
StormEvents_1984 <- StormEvents_1984|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1985}
StormEvents_1985 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1985_c20250520.csv")
StormEvents_1985 <- StormEvents_1985|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1986}
StormEvents_1986 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1986_c20250520.csv")
StormEvents_1986 <- StormEvents_1986|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1987}
StormEvents_1987 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1987_c20250520.csv")
StormEvents_1987 <- StormEvents_1987|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1988}
StormEvents_1988 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1988_c20250520.csv")
StormEvents_1988 <- StormEvents_1988|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1989}
StormEvents_1989 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1989_c20250520.csv")
StormEvents_1989 <- StormEvents_1989|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1990}
StormEvents_1990 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1990_c20250520.csv")
StormEvents_1990 <- StormEvents_1990|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1991}
StormEvents_1991 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1991_c20250520.csv")
StormEvents_1991 <- StormEvents_1991|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1992}
StormEvents_1992 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1992_c20250520.csv")
StormEvents_1992 <- StormEvents_1992|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1993}
StormEvents_1993 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1993_c20250520.csv")
StormEvents_1993 <- StormEvents_1993|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1994}
StormEvents_1994 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1994_c20250520.csv")
StormEvents_1994 <- StormEvents_1994|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1995}
StormEvents_1995 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1995_c20250520.csv")
StormEvents_1995 <- StormEvents_1995|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1996}
StormEvents_1996 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1996_c20250520.csv")
StormEvents_1996 <- StormEvents_1996|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1997}
StormEvents_1997 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1997_c20250520.csv")
StormEvents_1997 <- StormEvents_1997|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1998}
StormEvents_1998 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1998_c20250520.csv")
StormEvents_1998 <- StormEvents_1998|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 1999}
StormEvents_1999 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d1999_c20250520.csv")
StormEvents_1999 <- StormEvents_1999|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2000}
StormEvents_2000 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2000_c20250520.csv")
StormEvents_2000 <- StormEvents_2000|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2001}
StormEvents_2001 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2001_c20250520.csv")
StormEvents_2001 <- StormEvents_2001|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2002}
StormEvents_2002 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2002_c20250520.csv")
StormEvents_2002 <- StormEvents_2002|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2003}
StormEvents_2003 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2003_c20250520.csv")
StormEvents_2003 <- StormEvents_2003|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2004}
StormEvents_2004 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2004_c20250520.csv")
StormEvents_2004 <- StormEvents_2004|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2005}
StormEvents_2005 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2005_c20250520.csv")
StormEvents_2005 <- StormEvents_2005|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2006}
StormEvents_2006 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2006_c20250520.csv")
StormEvents_2006 <- StormEvents_2006|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2007}
StormEvents_2007 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2007_c20250520.csv")
StormEvents_2007 <- StormEvents_2007|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2008}
StormEvents_2008 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2008_c20250520.csv")
StormEvents_2008 <- StormEvents_2008|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2009}
StormEvents_2009 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2009_c20250520.csv")
StormEvents_2009 <- StormEvents_2009|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2010}
StormEvents_2010 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2010_c20250520.csv")
StormEvents_2010 <- StormEvents_2010|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2011}
StormEvents_2011 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2011_c20250520.csv")
StormEvents_2011 <- StormEvents_2011|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2012}
StormEvents_2012 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2012_c20250520.csv")
StormEvents_2012 <- StormEvents_2012|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2013}
StormEvents_2013 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2013_c20250520.csv")
StormEvents_2013 <- StormEvents_2013|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2014}
StormEvents_2014 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2014_c20250520.csv")
StormEvents_2014 <- StormEvents_2014|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2015}
StormEvents_2015 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2015_c20250818.csv")
StormEvents_2015 <- StormEvents_2015|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2016}
StormEvents_2016 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2016_c20250818.csv")
StormEvents_2016 <- StormEvents_2016|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2017}
StormEvents_2017 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2017_c20250520.csv")
StormEvents_2017 <- StormEvents_2017|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2018}
StormEvents_2018 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2018_c20250520.csv")
StormEvents_2018 <- StormEvents_2018|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2019}
StormEvents_2019 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2019_c20250520.csv")
StormEvents_2019 <- StormEvents_2019|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2020}
StormEvents_2020 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2020_c20250702.csv")
StormEvents_2020 <- StormEvents_2020|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2021}
StormEvents_2021 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2021_c20250520.csv")
StormEvents_2021 <- StormEvents_2021|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2022}
StormEvents_2022 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2022_c20250721.csv")
StormEvents_2022 <- StormEvents_2022|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2023}
StormEvents_2023 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2023_c20250731.csv")
StormEvents_2023 <- StormEvents_2023|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r 2024}
StormEvents_2024 <- read_csv("../data/ignore/StormEvents_details-ftp_v1.0_d2024_c20250818.csv")
StormEvents_2024 <- StormEvents_2024|>
select (-EPISODE_ID, -CZ_TYPE, -CZ_FIPS, -CZ_NAME, -WFO, -BEGIN_DATE_TIME, -CZ_TIMEZONE,
-END_DATE_TIME, -MAGNITUDE_TYPE, -TOR_LENGTH, -TOR_WIDTH, -TOR_OTHER_WFO, -TOR_OTHER_CZ_FIPS,
-TOR_OTHER_CZ_NAME, -BEGIN_RANGE, -BEGIN_AZIMUTH, -BEGIN_LOCATION, -END_RANGE,	-END_AZIMUTH,
-END_LOCATION, -EPISODE_NARRATIVE, -EVENT_NARRATIVE)
```

```{r rbind}
all_storms <- rbind(StormEvents_1950,
                    StormEvents_1951,
                    StormEvents_1952,
                    StormEvents_1953,
                    StormEvents_1954,
                    StormEvents_1955,
                    StormEvents_1956,
                    StormEvents_1957,
                    StormEvents_1958,
                    StormEvents_1959,
                    StormEvents_1960,
                    StormEvents_1961,
                    StormEvents_1962,
                    StormEvents_1963,
                    StormEvents_1964,
                    StormEvents_1965,
                    StormEvents_1966,
                    StormEvents_1967,
                    StormEvents_1968,
                    StormEvents_1969,
                    StormEvents_1970,
                    StormEvents_1971,
                    StormEvents_1972,
                    StormEvents_1973,
                    StormEvents_1974,
                    StormEvents_1975,
                    StormEvents_1976,
                    StormEvents_1977,
                    StormEvents_1978,
                    StormEvents_1979,
                    StormEvents_1980,
                    StormEvents_1981,
                    StormEvents_1982,
                    StormEvents_1983,
                    StormEvents_1984,
                    StormEvents_1985,
                    StormEvents_1986,
                    StormEvents_1987,
                    StormEvents_1988,
                    StormEvents_1989,
                    StormEvents_1990,
                    StormEvents_1991,
                    StormEvents_1992,
                    StormEvents_1993,
                    StormEvents_1994,
                    StormEvents_1995,
                    StormEvents_1996,
                    StormEvents_1997,
                    StormEvents_1998,
                    StormEvents_1999,
                    StormEvents_2000,
                    StormEvents_2001,
                    StormEvents_2002,
                    StormEvents_2003,
                    StormEvents_2004,
                    StormEvents_2005,
                    StormEvents_2006,
                    StormEvents_2007,
                    StormEvents_2008,
                    StormEvents_2009,
                    StormEvents_2010,
                    StormEvents_2011,
                    StormEvents_2012,
                    StormEvents_2013,
                    StormEvents_2014,
                    StormEvents_2015,
                    StormEvents_2016,
                    StormEvents_2017,
                    StormEvents_2018,
                    StormEvents_2019,
                    StormEvents_2020,
                    StormEvents_2021,
                    StormEvents_2022,
                    StormEvents_2023,
                    StormEvents_2024)
write_csv(all_storms, file="../data/ignore/all-storms.csv")
```

```{r read_csv}
all_storms <- read.csv("../data/ignore/all-storms.csv")
```

```{r remove-least_common}
least_common <- all_storms|>
  count(EVENT_TYPE)|>
  arrange(n)

#exclude  n < 1000
all_storms <- all_storms|>
  filter(!EVENT_TYPE %in% c("Volcanic Ashfall", "Tsunami", "Lakeshore Flood", "Dense Smoke",
                             "Northern Lights", "Seiche", "Volcanic Ash", "Dust Devil", 
                            "Astronomical Low Tide", "Freezing Fog", "Tropical Depression", 
                            "Avalanche", "Dust Storm", "Sleet", "Debris Flow", "Rip Current" ,
                            "Lake-Effect Snow", "Storm Surge/Tide", "Sneakerwave",""))

write_csv(all_storms, file="../data/ignore/all-storms.csv")


all_storms|>
  count(EVENT_TYPE)|>
  arrange(n)
```


```{r earliest}

earliest_storms <- all_storms|>
  select(YEAR, EVENT_TYPE)|>
  group_by(EVENT_TYPE)|>
  summarise(min_year = min(YEAR))|>
  arrange(min_year)
  


print(earliest_storms)
```

