---
title: "Tornado Analysis"
output: html_document
---

```{r libraries}
library(tidyverse)
library(ggridges)
```

```{r filter-tornadoes, message = FALSE}

tornadoes <- read_csv("../data/ignore/all-storms.csv")

tornadoes <- tornadoes |>
  filter(EVENT_TYPE == "Tornado")|>
  select(EVENT_ID, STATE, STATE_FIPS, YEAR, INJURIES_DIRECT, INJURIES_INDIRECT, 
         DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGE_PROPERTY, DAMAGE_CROPS, TOR_F_SCALE, BEGIN_LAT, BEGIN_LON)

```

```{r tornadoes-per-year_cleaning}
tornadoes_per_year <- tornadoes|>
  count(YEAR, name = "n_events")
```

```{r tornadoes_per_year}
ggplot(tornadoes_per_year, aes(x = YEAR, y = n_events)) +
  geom_smooth(method = "lm")+
  geom_line(linewidth = .8) +
  geom_point(size = 1.5) +
  labs(
    title = "Number of tornadoes in the US per year (1950-2024)",
    subtitle = "Filtered to major natural disasters",
    x = "Year",
    y = "Number of Events"
  ) +
  theme_minimal()+
  scale_x_continuous(breaks = c(1950,1960,1970,1980,1990,2000,2010,2020))

```

```{r tornado-type-cleaning}

tornado_scale <- tornadoes |>
  select(YEAR, TOR_F_SCALE)|>
  group_by(TOR_F_SCALE, YEAR)|>
  count(TOR_F_SCALE, name = "n_events")|>
  filter(!(TOR_F_SCALE == "EFU"))|>
  arrange(YEAR)

tornado_scale <- na.omit(tornado_scale)
tornado_scale[tornado_scale == "F0"] <- "EF0"
tornado_scale[tornado_scale == "F1"] <- "EF1"
tornado_scale[tornado_scale == "F2"] <- "EF2"
tornado_scale[tornado_scale == "F3"] <- "EF3"
tornado_scale[tornado_scale == "F4"] <- "EF4"
tornado_scale[tornado_scale == "F5"] <- "EF5"



```



```{r tornadoes_by_category}
ggplot(tornado_scale, aes(x = YEAR, y = n_events, fill = TOR_F_SCALE)) +
  geom_density_ridges() +
  labs(
    title = "Number of tornadoes in the US per year (1950-2024)",
    subtitle = "Filtered to major natural disasters",
    x = "Year",
    y = "Number of Events"
  ) +
  theme_minimal()
  #scale_y_continuous(trans=scales::pseudo_log_trans(base = 20))
```